name: Tests

on:
  #push:
  #  branches: [main]
  pull_request:
  #schedule:
  #  - cron: '0 9 * * *'

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"

    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']

    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: composer-dependencies-php-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Execute PHPUnit
        run: ./vendor/bin/phpunit
